# Generated by Django 5.2 on 2025-05-03 15:38

import django.db.models.functions.text
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "text",
                    models.CharField(
                        help_text="The question itself", max_length=100, unique=True
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        help_text="Explain the question to the user",
                        max_length=200,
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(auto_now=True, help_text="Modification time"),
                ),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, help_text="Creation time"),
                ),
            ],
            options={
                "ordering": ["created"],
                "constraints": [
                    models.UniqueConstraint(
                        django.db.models.functions.text.Lower("text"),
                        name="question_text_unique_ci",
                        violation_error_message="Same question text already exists (case-insensitive match)",
                    )
                ],
            },
        ),
    ]
